// Allow any host header and run dev server on port 8081 for tunneling (e.g. ngrok)
// This file augments the autogenerated webpack config produced by Kotlin/JS Gradle plugin.
// See: https://webpack.js.org/configuration/dev-server/

if (!config.devServer) {
  config.devServer = {};
}

config.devServer.allowedHosts = 'all';
config.devServer.host = '0.0.0.0';
config.devServer.headers = {
  'Access-Control-Allow-Origin': '*',
};

